package dev.jakubzika.befair.ui.atoms
import androidx.compose.ui.graphics.Color

/************************/
/***** LIGHT COLORS *****/
/************************/

val primaryLight = Color(0xFF004CCD)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF0F62FE)
val onPrimaryContainerLight = Color(0xFFF3F3FF)
val secondaryLight = Color(0xFF445BA1)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF9DB3FF)
val onSecondaryContainerLight = Color(0xFF2B4388)
val tertiaryLight = Color(0xFF8E18B0)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFAA3BCB)
val onTertiaryContainerLight = Color(0xFFFFF0FD)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFAF8FF)
val onBackgroundLight = Color(0xFF191B24)
val surfaceLight = Color(0xFFFAF8FF)
val onSurfaceLight = Color(0xFF191B24)
val surfaceVariantLight = Color(0xFFDFE1F5)
val onSurfaceVariantLight = Color(0xFF424656)
val outlineLight = Color(0xFF737687)
val outlineVariantLight = Color(0xFFC3C6D8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E303A)
val inverseOnSurfaceLight = Color(0xFFEFF0FD)
val inversePrimaryLight = Color(0xFFB4C5FF)
val surfaceDimLight = Color(0xFFD8D9E6)
val surfaceBrightLight = Color(0xFFFAF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F3FF)
val surfaceContainerLight = Color(0xFFECEDFA)
val surfaceContainerHighLight = Color(0xFFE7E7F4)
val surfaceContainerHighestLight = Color(0xFFE1E1EE)


/************************/
/***** DARK COLORS *****/
/************************/

val primaryDark = Color(0xFFB4C5FF)
val onPrimaryDark = Color(0xFF002979)
val primaryContainerDark = Color(0xFF0F62FE)
val onPrimaryContainerDark = Color(0xFFF3F3FF)
val secondaryDark = Color(0xFFB4C5FF)
val onSecondaryDark = Color(0xFF0E2B6F)
val secondaryContainerDark = Color(0xFF2D458A)
val onSecondaryContainerDark = Color(0xFFA0B6FF)
val tertiaryDark = Color(0xFFF1AFFF)
val onTertiaryDark = Color(0xFF55006C)
val tertiaryContainerDark = Color(0xFFAA3BCB)
val onTertiaryContainerDark = Color(0xFFFFF0FD)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF11131C)
val onBackgroundDark = Color(0xFFE1E1EE)
val surfaceDark = Color(0xFF11131C)
val onSurfaceDark = Color(0xFFE1E1EE)
val surfaceVariantDark = Color(0xFF424656)
val onSurfaceVariantDark = Color(0xFFC3C6D8)
val outlineDark = Color(0xFF8C90A2)
val outlineVariantDark = Color(0xFF424656)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E1EE)
val inverseOnSurfaceDark = Color(0xFF2E303A)
val inversePrimaryDark = Color(0xFF0052DD)
val surfaceDimDark = Color(0xFF11131C)
val surfaceBrightDark = Color(0xFF373943)
val surfaceContainerLowestDark = Color(0xFF0B0E16)
val surfaceContainerLowDark = Color(0xFF191B24)
val surfaceContainerDark = Color(0xFF1D1F28)
val surfaceContainerHighDark = Color(0xFF272A33)
val surfaceContainerHighestDark = Color(0xFF32343E)
