package dev.jakubzika.befair.ui.atoms

import androidx.compose.ui.graphics.Color

/************************/
/***** LIGHT COLORS *****/
/************************/

val primaryLight = Color(0xFF005050)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF006A6A)
val onPrimaryContainerLight = Color(0xFF97E7E6)
val secondaryLight = Color(0xFF4A6363)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCCE8E7)
val onSecondaryContainerLight = Color(0xFF506969)
val tertiaryLight = Color(0xFF334863)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF4B607C)
val onTertiaryContainerLight = Color(0xFFC5DBFB)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF8FAFA)
val onBackgroundLight = Color(0xFF191C1D)
val surfaceLight = Color(0xFFF8FAFA)
val onSurfaceLight = Color(0xFF191C1D)
val surfaceVariantLight = Color(0xFFE1E3E3)
val onSurfaceVariantLight = Color(0xFF3E4948)
val outlineLight = Color(0xFF6E7979)
val outlineVariantLight = Color(0xFFBEC9C8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3131)
val inverseOnSurfaceLight = Color(0xFFEFF1F1)
val inversePrimaryLight = Color(0xFF84D4D3)
val surfaceDimLight = Color(0xFFD8DADA)
val surfaceBrightLight = Color(0xFFF8FAFA)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F4F4)
val surfaceContainerLight = Color(0xFFECEEEE)
val surfaceContainerHighLight = Color(0xFFE6E8E9)
val surfaceContainerHighestLight = Color(0xFFE1E3E3)

// Fixed colors — identical across light and dark per M3 spec
val primaryFixedLight = Color(0xFFA0F0F0)
val primaryFixedDimLight = Color(0xFF84D4D3)
val onPrimaryFixedLight = Color(0xFF002020)
val onPrimaryFixedVariantLight = Color(0xFF004F4F)
val secondaryFixedLight = Color(0xFFCCE8E7)
val secondaryFixedDimLight = Color(0xFFB1CCCB)
val onSecondaryFixedLight = Color(0xFF051F20)
val onSecondaryFixedVariantLight = Color(0xFF324B4B)
val tertiaryFixedLight = Color(0xFFD2E4FF)
val tertiaryFixedDimLight = Color(0xFFB2C8E8)
val onTertiaryFixedLight = Color(0xFF031C35)
val onTertiaryFixedVariantLight = Color(0xFF334863)

/***********************/
/***** DARK COLORS *****/
/***********************/

val primaryDark = Color(0xFF84D4D3)
val onPrimaryDark = Color(0xFF003737)
val primaryContainerDark = Color(0xFF004F4F)
val onPrimaryContainerDark = Color(0xFF9DECEB)
val secondaryDark = Color(0xFFB1CCCB)
val onSecondaryDark = Color(0xFF1C3535)
val secondaryContainerDark = Color(0xFF324B4B)
val onSecondaryContainerDark = Color(0xFFCDE9E8)
val tertiaryDark = Color(0xFFB2C8E8)
val onTertiaryDark = Color(0xFF1C3149)
val tertiaryContainerDark = Color(0xFF334863)
val onTertiaryContainerDark = Color(0xFFD2E4FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF101414)
val onBackgroundDark = Color(0xFFE1E3E3)
val surfaceDark = Color(0xFF101414)
val onSurfaceDark = Color(0xFFE1E3E3)
val surfaceVariantDark = Color(0xFF3E4948)
val onSurfaceVariantDark = Color(0xFFBEC9C8)
val outlineDark = Color(0xFF889392)
val outlineVariantDark = Color(0xFF3E4948)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E3E3)
val inverseOnSurfaceDark = Color(0xFF2E3131)
val inversePrimaryDark = Color(0xFF005050)
val surfaceDimDark = Color(0xFF101414)
val surfaceBrightDark = Color(0xFF363A3A)
val surfaceContainerLowestDark = Color(0xFF0B0F0F)
val surfaceContainerLowDark = Color(0xFF191C1D)
val surfaceContainerDark = Color(0xFF1D2020)
val surfaceContainerHighDark = Color(0xFF272B2B)
val surfaceContainerHighestDark = Color(0xFF323535)

// Fixed colors — identical across light and dark per M3 spec
val primaryFixedDark = Color(0xFFA0F0F0)
val primaryFixedDimDark = Color(0xFF84D4D3)
val onPrimaryFixedDark = Color(0xFF002020)
val onPrimaryFixedVariantDark = Color(0xFF004F4F)
val secondaryFixedDark = Color(0xFFCCE8E7)
val secondaryFixedDimDark = Color(0xFFB1CCCB)
val onSecondaryFixedDark = Color(0xFF051F20)
val onSecondaryFixedVariantDark = Color(0xFF324B4B)
val tertiaryFixedDark = Color(0xFFD2E4FF)
val tertiaryFixedDimDark = Color(0xFFB2C8E8)
val onTertiaryFixedDark = Color(0xFF031C35)
val onTertiaryFixedVariantDark = Color(0xFF334863)
